# Generated by Django 3.1 on 2020-08-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petition',
            options={'verbose_name': '건국 시무 청원', 'verbose_name_plural': '건국 시무 청원'},
        ),
        migrations.AlterModelTable(
            name='petition',
            table='simu_petition',
        ),
    ]
