# Generated by Django 3.1 on 2020-08-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0002_auto_20200829_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='accept_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='petition',
            name='agree_count',
            field=models.IntegerField(default=0),
        ),
    ]
