# Generated by Django 3.1 on 2020-08-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_has_module_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_module_perms',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
